version: "3"
services:

  redis:
    container_name: redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres

  web:
    build: .
    command: /bin/sh -c "entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - redis

volumes:
    redis-data:
    pgdata:
